version: '3'

tasks:
  prepare: pnpm install

  build:
    - task: stream:build
    - task: renderer:build
    - task: console-renderer:build
    - task: vdom-renderer:build
    - task: framework:build
    - task: counter:build
    - task: random-cat:build

  dev-counter:
    deps:
      - stream:watch
      - renderer:watch
      - console-renderer:watch
      - vdom-renderer:watch
      - framework:watch
      - counter:dev

  dev-random-cat:
    deps:
      - stream:watch
      - renderer:watch
      - console-renderer:watch
      - vdom-renderer:watch
      - framework:watch
      - random-cat:dev

includes:
  stream:
    taskfile: ./packages/stream/Taskfile.yml
    dir: ./packages/stream

  renderer:
    taskfile: ./packages/renderer/Taskfile.yml
    dir: ./packages/renderer

  console-renderer:
    taskfile: ./packages/console-renderer/Taskfile.yml
    dir: ./packages/console-renderer

  vdom-renderer:
    taskfile: ./packages/vdom-renderer/Taskfile.yml
    dir: ./packages/vdom-renderer

  framework:
    taskfile: ./packages/framework/Taskfile.yml
    dir: ./packages/framework

  counter:
    taskfile: ./packages/examples/counter/Taskfile.yml
    dir: ./packages/examples/counter

  random-cat:
    taskfile: ./packages/examples/random-cat/Taskfile.yml
    dir: ./packages/examples/random-cat
