version: '3'

tasks:
  prepare: pnpm install

  build:
    - task: renderer:build
    - task: vdom-renderer:build
    - task: framework:build
    - task: counter:build
    - task: random-cat:build

  dev-counter:
    deps:
      - renderer:watch
      - vdom-renderer:watch
      - framework:watch
      - counter:dev

  dev-random-cat:
    deps:
      - renderer:watch
      - vdom-renderer:watch
      - framework:watch
      - random-cat:dev

  dev-hello-world:
    deps:
      - renderer:watch
      - vdom-renderer:watch
      - framework:watch
      - hello-world:dev

includes:
  renderer:
    taskfile: ./packages/renderer/Taskfile.yml
    dir: ./packages/renderer

  vdom-renderer:
    taskfile: ./packages/vdom-renderer/Taskfile.yml
    dir: ./packages/vdom-renderer

  framework:
    taskfile: ./packages/framework/Taskfile.yml
    dir: ./packages/framework

  counter:
    taskfile: ./packages/examples/counter/Taskfile.yml
    dir: ./packages/examples/counter

  random-cat:
    taskfile: ./packages/examples/random-cat/Taskfile.yml
    dir: ./packages/examples/random-cat

  hello-world:
    taskfile: ./packages/examples/hello-world/Taskfile.yml
    dir: ./packages/examples/hello-world
